# Generated by Django 4.0.4 on 2022-07-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttable',
            name='content_file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
